test: ethernet-interface: fix compile error with GCC16
A compile failure was introduced in 411945f1ce8 on GCC16
due to using string_view and underlying sdbusplus generated bindings not
supporting string_view.  Since this is a test case, that was an
over-optimization anyhow and not necessary.  Switch the test case to use
a simple `std::string` which compiles and passes.

Example failure:
```
In file included from ../test/test_ethernet_interface.cpp:3:
../test/mock_ethernet_interface.hpp: In instantiation of ‘phosphor::network::MockEthernetInterface::MockEthernetInterface(Args&& ...) [with Args = {stdplus::Pinned<sdbusplus::bus_t, sdbusplus::bus_t>&, phosphor::network::TestManager&, phosphor::network::AllIntfInfo&, std::basic_string_view<char, std::char_traits<char> >, phosphor::network::config::Parser}]’:
../test/test_ethernet_interface.cpp:500:5:   required from here
  502 |                               config::Parser()),
      |                                               ^
../test/mock_ethernet_interface.hpp:15:75: error: no matching function for call to ‘phosphor::network::EthernetInterface::EthernetInterface(stdplus::Pinned<sdbusplus::bus_t>&, phosphor::network::TestManager&, phosphor::network::AllIntfInfo&, std::basic_string_view<char>, phosphor::network::config::Parser, bool)’
   15 |         EthernetInterface(std::forward<Args>(args)..., /*nicEnabled=*/true)
      |                                                                           ^
      ...
      • no known conversion for argument 4 from ‘std::basic_string_view<char>’ to ‘const sdbusplus::object_path&’ {aka ‘const sdbusplus::message::details::string_path_wrapper&’}
        ../src/ethernet_interface.hpp:91:53:
           91 |                       const sdbusplus::object_path& objRoot,
              |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
```

Fixes: 411945f1ce8c ("ethernet_interface: fix missing throw in VLAN check")
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Ieabcb0a790aa31e64e003ae5ee5dcc1ed3fb556f