system-queries: fix missing header
Add `unistd.h` to resolve the `close` identifier error.

```
../src/system_queries.cpp: In lambda function:
../src/system_queries.cpp:169:21: error: there are no arguments to ‘close’ that depend on a template parameter, so a declaration of ‘close’ must be available [-Wtemplate-body]
  169 |                     close(sock);
      |                     ^~~~~
../src/system_queries.cpp:169:21: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../src/system_queries.cpp:199:21: error: there are no arguments to ‘close’ that depend on a template parameter, so a declaration of ‘close’ must be available [-Wtemplate-body]
  199 |                     close(sock);
      |                     ^~~~~
../src/system_queries.cpp:205:17: error: there are no arguments to ‘close’ that depend on a template parameter, so a declaration of ‘close’ must be available [-Wtemplate-body]
  205 |                 close(sock);
      |                 ^~~~~
```

This was observed with the latest Yocto upgrade and also on an
independent system having GCC-16.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I42756085f456a133b7f4d35c023c66314ddc3afe