fix include for std::memcpy
Got this compilation error on GCC 16, fixed by including the required
header <cstring> [1]

```
../src/system_queries.cpp: In lambda function:
../src/system_queries.cpp:190:22: error: ‘memcpy’ is not a member of ‘std’; did you mean ‘wmemcpy’? [-Wtemplate-body]
  190 |                 std::memcpy(RTA_DATA(rta), &addr, sizeof(in_addr));
      |                      ^~~~~~
      |                      wmemcpy
```

References:
[1] https://en.cppreference.com/cpp/string/byte/memcpy

Change-Id: I7cf14ac370768dba37bdabf7badc23494da9f9f2
Signed-off-by: Alexander Hansen <alexander.hansen@9elements.com>